--------------------------------------------------------
--  DDL for Table AUDIT_DDL_CHANGE
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."AUDIT_DDL_CHANGE" 
   (	"ID" NUMBER(10,0), 
	"OBJECT_NAME" VARCHAR2(255 CHAR), 
	"OBJECT_TYPE" VARCHAR2(255 CHAR), 
	"OSUSER" VARCHAR2(255 CHAR), 
	"DDL_TIME" DATE, 
	"ACTION" VARCHAR2(255 CHAR), 
	"OSMACHINE" VARCHAR2(4000 CHAR), 
	"PREV_TEXT" CLOB, 
	"TEXT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_DATA" 
 LOB ("PREV_TEXT") STORE AS SECUREFILE (
  TABLESPACE "TEST_DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TEXT") STORE AS SECUREFILE (
  TABLESPACE "TEST_DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."ID" IS 'ID';
   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."OBJECT_NAME" IS 'Наименование объекта';
   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."OBJECT_TYPE" IS 'Тип объекта';
   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."OSUSER" IS 'Пользователь ОС';
   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."DDL_TIME" IS 'Дата изменения';
   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."ACTION" IS 'Событие';
   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."OSMACHINE" IS 'Имя ПК';
   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."PREV_TEXT" IS 'Предыдущий текст объекта';
   COMMENT ON COLUMN "TEST_USER"."AUDIT_DDL_CHANGE"."TEXT" IS 'Измененный текст объекта';
   COMMENT ON TABLE "TEST_USER"."AUDIT_DDL_CHANGE"  IS 'Аудит изменения объектов на тестовой базе';
