--------------------------------------------------------
--  DDL for Table CURRENCY
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."CURRENCY" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODE" VARCHAR2(3 CHAR), 
	"NAME" VARCHAR2(50 CHAR), 
	"SHORT_NAME" VARCHAR2(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_DATA" ;

   COMMENT ON COLUMN "TEST_USER"."CURRENCY"."ID" IS 'ID';
   COMMENT ON COLUMN "TEST_USER"."CURRENCY"."CODE" IS 'Код валюты НБУ (980,840)';
   COMMENT ON COLUMN "TEST_USER"."CURRENCY"."NAME" IS 'Наименование валюты';
   COMMENT ON COLUMN "TEST_USER"."CURRENCY"."SHORT_NAME" IS 'Код валюты НБУ текстовый (UAH,USD)';
   COMMENT ON TABLE "TEST_USER"."CURRENCY"  IS 'Коды валют НБУ';
