--------------------------------------------------------
--  Constraints for Table FAIR_VALUE
--------------------------------------------------------

  ALTER TABLE "TEST_USER"."FAIR_VALUE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."FAIR_VALUE" MODIFY ("CALC_DATE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."FAIR_VALUE" MODIFY ("ISIN" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."FAIR_VALUE" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEST_USER"."FAIR_VALUE" ADD CONSTRAINT "FAIR_VALUE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_DATA"  ENABLE;
