--------------------------------------------------------
--  DDL for Index FAIR_VALUE_INDEX_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST_USER"."FAIR_VALUE_INDEX_UK" ON "TEST_USER"."FAIR_VALUE" ("CALC_DATE", "ISIN", "CURRENCY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_DATA" ;
