--------------------------------------------------------
--  File created - воскресенье-декабря-12-2021   
--------------------------------------------------------
@C:\sqldeveloper\export\T_ERB_MINFIN_ROW.sql
@C:\sqldeveloper\export\T_ERB_MINFIN_TABLE.sql
@C:\sqldeveloper\export\T_FAIR_VALUE_ROW.sql
@C:\sqldeveloper\export\T_FAIR_VALUE_TABLE.sql
@C:\sqldeveloper\export\T_ISIN_SECUR_ROW.sql
@C:\sqldeveloper\export\T_ISIN_SECUR_TABLE.sql
@C:\sqldeveloper\export\T_KURS_NBU_ROW.sql
@C:\sqldeveloper\export\T_KURS_NBU_TABLE.sql
@C:\sqldeveloper\export\AUDIT_DDL_CHANGE_SEQ.sql
@C:\sqldeveloper\export\KURS_SEQ.sql
@C:\sqldeveloper\export\AUDIT_DDL_CHANGE.sql
@C:\sqldeveloper\export\KURS.sql
@C:\sqldeveloper\export\VIEW_KURS_REPORT.sql
@C:\sqldeveloper\export\I_AUDIT_DDL_CHANGE_OBJ.sql
@C:\sqldeveloper\export\UK_KURS.sql
@C:\sqldeveloper\export\PK_KURS.sql
@C:\sqldeveloper\export\I_AUDIT_DDL_CHANGE_DT.sql
@C:\sqldeveloper\export\PK_AUDIT_DDL_CHANGE.sql
@C:\sqldeveloper\export\I_AUDIT_DDL_CHANGE_OBJT.sql
@C:\sqldeveloper\export\TR_AUDIT_DDL_BEFORE.sql
@C:\sqldeveloper\export\TR_AUDIT_DDL_CHANGE_BEFORE.sql
@C:\sqldeveloper\export\HTTP_REQUEST.sql
@C:\sqldeveloper\export\INSERT_KURS.sql
@C:\sqldeveloper\export\READ_WALLET_PARAM.sql
@C:\sqldeveloper\export\P_CHECK.sql
@C:\sqldeveloper\export\P_CONVERT.sql
@C:\sqldeveloper\export\P_INTERFACE.sql
@C:\sqldeveloper\export\P_INTERFACE_PIPE.sql
@C:\sqldeveloper\export\P_CHECK_1.sql
@C:\sqldeveloper\export\P_CONVERT_1.sql
@C:\sqldeveloper\export\P_INTERFACE_1.sql
@C:\sqldeveloper\export\P_INTERFACE_PIPE_1.sql
@C:\sqldeveloper\export\EXAMPLE_JSON_ARRAYAGG.sql
@C:\sqldeveloper\export\AUDIT_DDL_CHANGE_CONSTRAINT.sql
@C:\sqldeveloper\export\KURS_CONSTRAINT.sql
