--------------------------------------------------------
--  DDL for Table ISIN_SECUR
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."ISIN_SECUR" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ISIN" VARCHAR2(30 CHAR), 
	"NOMINAL" NUMBER(10,0), 
	"AUK_PROC" NUMBER, 
	"PGS_DATE" DATE, 
	"RAZM_DATE" DATE, 
	"CPTYPE" VARCHAR2(255 CHAR), 
	"CPDESCR" VARCHAR2(255 CHAR), 
	"PAY_PERIOD" NUMBER(10,0), 
	"CURRENCY_CODE" VARCHAR2(3 CHAR), 
	"EMIT_OKPO" VARCHAR2(255 CHAR), 
	"EMIT_NAME" VARCHAR2(255 CHAR), 
	"CPTYPE_NKCPFR" VARCHAR2(255 CHAR), 
	"CPCODE_CFI" VARCHAR2(255 CHAR), 
	"TOTAL_BONDS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_DATA" ;

   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."ID" IS 'ID';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."ISIN" IS 'ISIN';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."NOMINAL" IS 'Номинал';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."AUK_PROC" IS '% ставка';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."PGS_DATE" IS 'Дата погашения';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."RAZM_DATE" IS 'Дата размещения';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."CPTYPE" IS 'Тип ЦБ';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."CPDESCR" IS 'Описание';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."PAY_PERIOD" IS 'Платежный период';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."CURRENCY_CODE" IS 'Код валюты';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."EMIT_OKPO" IS 'ОКПО эммитента';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR"."EMIT_NAME" IS 'Наименование эммитента';
   COMMENT ON TABLE "TEST_USER"."ISIN_SECUR"  IS 'ISIN ЦБ';
