--------------------------------------------------------
--  DDL for Table ISIN_SECUR_PAY
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."ISIN_SECUR_PAY" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ISIN_SECUR_ID" NUMBER, 
	"PAY_DATE" DATE, 
	"PAY_TYPE" NUMBER(10,0), 
	"PAY_VAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_DATA" ;

   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR_PAY"."ID" IS 'ID';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR_PAY"."ISIN_SECUR_ID" IS 'ISIN_SECUR.ID';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR_PAY"."PAY_DATE" IS 'Дата выплаты';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR_PAY"."PAY_TYPE" IS 'Тип выплаты';
   COMMENT ON COLUMN "TEST_USER"."ISIN_SECUR_PAY"."PAY_VAL" IS 'Сумма выплаты на 1 ЦБ';
   COMMENT ON TABLE "TEST_USER"."ISIN_SECUR_PAY"  IS 'ISIN ЦБ - купонные периоды';
