--------------------------------------------------------
--  DDL for Table KURS
--------------------------------------------------------

  CREATE TABLE "TEST_USER"."KURS" 
   (	"ID" NUMBER(10,0), 
	"KURS_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"RATE" NUMBER(38,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_DATA" ;

   COMMENT ON COLUMN "TEST_USER"."KURS"."ID" IS 'ID';
   COMMENT ON COLUMN "TEST_USER"."KURS"."KURS_DATE" IS 'Дата курса';
   COMMENT ON COLUMN "TEST_USER"."KURS"."CURRENCY_CODE" IS 'Код валюты';
   COMMENT ON COLUMN "TEST_USER"."KURS"."RATE" IS 'Курс';
   COMMENT ON TABLE "TEST_USER"."KURS"  IS 'Курсы валют';
