    INSERT INTO CURRENCY (CODE,NAME,SHORT_NAME) VALUES ('980','Гривня','UAH');
    INSERT INTO CURRENCY (CODE,NAME,SHORT_NAME) VALUES ('840','Долар США','USD');
    INSERT INTO CURRENCY (CODE,NAME,SHORT_NAME) VALUES ('978','Євро','EUR');
    INSERT INTO CURRENCY (CODE,NAME,SHORT_NAME) VALUES ('826','Фунт стерлінгів','GBP');
    commit;
